# Project information
site_name: KlipperLH
site_url: https://ombayley.github.io/KlipperLH/
site_author: Olly Bayley
site_description: >-
  Custom built CoreXY liquid handling system based on the Klipper software stack used by open-source 3D printers

# Repository
repo_name: ombayley/KlipperLH
repo_url: https://github.com/ombayley/KlipperLH

# Copyright
copyright: Copyright &copy; 2026 Olly Bayley


edit_uri: edit/main/docs/
docs_dir: docs
site_dir: site
use_directory_urls: false

# Configuration
theme:
  name: material
  logo: imgs/klipper_logo.png
  icon:
    repo: fontawesome/brands/github
    logo: logo
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - toc.follow
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - User Guide:
      - 01 Raspberry Pi OS Install: user-guide/01-pi-install.md
      - 02 Networking: user-guide/02-networking.md
      - 03 Packages: user-guide/03-packages.md
      - 04 Klipper Flash: user-guide/04-klipper-flash.md
      - 05 Klipper Config: user-guide/05-klipper-config.md
      - 06 Moonraker Config: user-guide/06-moonraker-config.md
      - 07 Latency Improvements: user-guide/07-latency-improvements.md
      - 08 Testing and Bring-Up: user-guide/08-testing.md

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

exclude_docs: |
  user_guide_backup/

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ombayley/KlipperLH

validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    anchors: warn
    absolute_links: relative_to_docs
    unrecognized_links: warn
